/**
 * Cookie-fidelity property harness (Phase 0 go/kill exit criterion).
 * Schedules are generated by fast-check and executed deterministically —
 * no timers, no Math.random anywhere in the harness.
 */

import fc from "fast-check";
import { describe, expect, it } from "vitest";
import {
  compareHlc,
  encodeHlc,
  makeVersionToken,
  type CookieRecordWire,
} from "@pistachio/sync-protocol";
import {
  addReplica,
  attrsFor,
  createCluster,
  createEngine,
  enginePrint,
  identityAt,
  IDENTITY_POOL_SIZE,
  livePrint,
  makeIdentity,
  ManualClock,
  must,
  poolRecordIds,
  settle,
  testSpaceKeys,
  type Replica,
} from "./helpers.js";

const OP_KINDS = ["write", "overwrite", "explicit-delete", "expire"] as const;
type OpKind = (typeof OP_KINDS)[number];

type ConvergenceCmd =
  | { type: "op"; kind: OpKind; replica: number; ident: number }
  | { type: "deliver"; replica: number; count: number };

const opCmdArb: fc.Arbitrary<ConvergenceCmd> = fc
  .record({
    kind: fc.constantFrom(...OP_KINDS),
    replica: fc.integer({ min: 0, max: 3 }),
    ident: fc.integer({ min: 0, max: IDENTITY_POOL_SIZE - 1 }),
  })
  .map((op) => ({ type: "op", ...op }));

const deliverCmdArb: fc.Arbitrary<ConvergenceCmd> = fc
  .record({
    replica: fc.integer({ min: 0, max: 3 }),
    count: fc.integer({ min: 1, max: 6 }),
  })
  .map((d) => ({ type: "deliver", ...d }));

const cmdArb = fc.oneof(
  { arbitrary: opCmdArb, weight: 3 },
  { arbitrary: deliverCmdArb, weight: 2 },
);

async function runOp(
  cluster: Awaited<ReturnType<typeof createCluster>>,
  spaceId: string,
  cmd: Extract<ConvergenceCmd, { type: "op" }>,
  seq: number,
  replicaCount: number,
): Promise<void> {
  const replica = cluster.replicas[cmd.replica % replicaCount];
  if (!replica) return;
  const identity = identityAt(spaceId, cmd.ident);
  cluster.clock.tick(1);
  if (cmd.kind === "write") {
    await replica.engine.localChange(
      identity,
      attrsFor(`v${seq}`),
      false,
      "explicit",
    );
  } else if (cmd.kind === "overwrite") {
    await replica.engine.localChange(
      identity,
      attrsFor(`o${seq}`),
      false,
      "overwrite",
    );
  } else if (cmd.kind === "explicit-delete") {
    await replica.engine.localChange(identity, null, true, "explicit");
  } else {
    await replica.engine.localChange(identity, null, true, "expired");
  }
}

describe("property 1: convergence", () => {
  it("replicas converge to identical live sets and record maps under random schedules", async () => {
    const spaceId = "space-convergence";
    const recordIds = await poolRecordIds(
      await testSpaceKeys(spaceId),
      spaceId,
    );
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 2, max: 4 }),
        fc.array(cmdArb, { maxLength: 30 }),
        async (replicaCount, cmds) => {
          const cluster = await createCluster(spaceId, replicaCount);
          let seq = 0;
          for (const cmd of cmds) {
            if (cmd.type === "op") {
              seq += 1;
              await runOp(cluster, spaceId, cmd, seq, replicaCount);
            } else {
              await cluster.hub.deliver(
                `dev-${cmd.replica % replicaCount}`,
                cmd.count,
              );
            }
          }
          await cluster.hub.deliverAll();
          const prints = cluster.replicas.map((r) =>
            enginePrint(r.engine, recordIds),
          );
          const lives = cluster.replicas.map((r) => livePrint(r.engine));
          for (let i = 1; i < cluster.replicas.length; i += 1) {
            expect(prints[i]).toBe(prints[0]);
            expect(lives[i]).toBe(lives[0]);
          }
        },
      ),
      { numRuns: 40 },
    );
  }, 120_000);
});

describe("property 2: no resurrection", () => {
  it("scripted PRD scenario: explicit delete beats a later causally-ignorant write", async () => {
    const spaceId = "space-resurrection";
    const clock = new ManualClock();
    const a = await createEngine(spaceId, "dev-a", clock);
    const b = await createEngine(spaceId, "dev-b", clock);
    const c = await createEngine(spaceId, "dev-c", clock);
    const identity = makeIdentity(spaceId, "github.com", "sid");

    clock.tick(1);
    const w0 = must(
      await a.engine.localChange(identity, attrsFor("v0"), false, "explicit"),
    );
    expect(await b.engine.applyRemote([w0])).toEqual(["applied"]);
    expect(await c.engine.applyRemote([w0])).toEqual(["applied"]);

    clock.tick(1);
    const tombstone = must(
      await a.engine.localChange(identity, null, true, "explicit"),
    );
    expect(await c.engine.applyRemote([tombstone])).toEqual(["applied"]);

    // B is offline, never saw the delete, and writes with a LATER HLC.
    clock.tick(1);
    const stale = must(
      await b.engine.localChange(identity, attrsFor("v1"), false, "explicit"),
    );
    expect(compareHlc(stale.hlc, tombstone.hlc)).toBeGreaterThan(0);
    expect(stale.causalParent).toBe(makeVersionToken(w0.recordId, w0.hlc));

    expect(await a.engine.applyRemote([stale])).toEqual([
      "resurrection-blocked",
    ]);
    expect(await c.engine.applyRemote([stale])).toEqual([
      "resurrection-blocked",
    ]);
    expect(a.engine.listLiveCookies()).toEqual([]);
    expect(c.engine.listLiveCookies()).toEqual([]);

    // B receives the tombstone and also converges to deleted.
    expect(await b.engine.applyRemote([tombstone])).toEqual(["applied"]);
    expect(b.engine.listLiveCookies()).toEqual([]);
    for (const replica of [a, b, c]) {
      const record = must(replica.engine.getRecord(tombstone.recordId));
      expect(record.cause).toBe("EXPLICIT_DELETE");
      expect(encodeHlc(record.hlc)).toBe(encodeHlc(tombstone.hlc));
    }

    // A later write that DID see the logout is a legitimate re-login.
    clock.tick(1);
    const relogin = must(
      await b.engine.localChange(identity, attrsFor("v2"), false, "explicit"),
    );
    expect(relogin.causalParent).toBe(
      makeVersionToken(tombstone.recordId, tombstone.hlc),
    );
    expect(await a.engine.applyRemote([relogin])).toEqual(["applied"]);
    expect(a.engine.listLiveCookies()).toHaveLength(1);
  });

  it("holds as a property over random offline-write counts and delivery schedules", async () => {
    const spaceId = "space-resurrection-prop";
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 1, max: 3 }),
        fc.array(
          fc.record({
            replica: fc.integer({ min: 0, max: 2 }),
            count: fc.integer({ min: 1, max: 4 }),
          }),
          { maxLength: 8 },
        ),
        async (offlineWrites, deliveries) => {
          const cluster = await createCluster(spaceId, 3);
          const a = cluster.replicas[0];
          const b = cluster.replicas[1];
          if (!a || !b) throw new Error("cluster too small");
          const identity = identityAt(spaceId, 0);

          cluster.clock.tick(1);
          must(
            await a.engine.localChange(
              identity,
              attrsFor("v0"),
              false,
              "explicit",
            ),
          );
          await cluster.hub.deliverAll();

          cluster.clock.tick(1);
          const tombstone = must(
            await a.engine.localChange(identity, null, true, "explicit"),
          );

          // B never saw the delete; every write has pre-delete ancestry.
          for (let i = 0; i < offlineWrites; i += 1) {
            cluster.clock.tick(1);
            must(
              await b.engine.localChange(
                identity,
                attrsFor(`b${i}`),
                false,
                "explicit",
              ),
            );
          }

          for (const d of deliveries) {
            await cluster.hub.deliver(`dev-${d.replica}`, d.count);
          }
          await cluster.hub.deliverAll();

          for (const replica of cluster.replicas) {
            const record = must(replica.engine.getRecord(tombstone.recordId));
            expect(record.plain.deleted).toBe(true);
            expect(record.cause).toBe("EXPLICIT_DELETE");
            expect(encodeHlc(record.hlc)).toBe(encodeHlc(tombstone.hlc));
            expect(livePrint(replica.engine)).toBe("[]");
          }
        },
      ),
      { numRuns: 40 },
    );
  }, 120_000);
});

describe("property 3: hydration echo suppression", () => {
  it("hydrating a jar of K records publishes zero records", async () => {
    const spaceId = "space-hydration";
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 1, max: 6 }),
        fc.integer({ min: 0, max: 6 }),
        async (jarSize, splitRaw) => {
          const clock = new ManualClock();
          const source = await createEngine(spaceId, "dev-src", clock);
          const target = await createEngine(spaceId, "dev-tgt", clock);
          const wires: CookieRecordWire[] = [];
          for (let i = 0; i < jarSize; i += 1) {
            clock.tick(1);
            wires.push(
              must(
                await source.engine.localChange(
                  identityAt(spaceId, i),
                  attrsFor(`h${i}`),
                  false,
                  "explicit",
                ),
              ),
            );
          }
          const split = Math.min(splitRaw, jarSize);

          await target.engine.beginHydration();
          expect(
            await target.engine.applyRemote(wires.slice(0, split)),
          ).toEqual(new Array(split).fill("applied"));
          // Cookie-changed echoes arriving while hydration is still active.
          for (const entry of target.applier.applied.slice(0, split)) {
            expect(
              await target.engine.localChange(
                entry.plain.identity,
                entry.plain.attributes,
                false,
                "explicit",
              ),
            ).toBeNull();
          }
          await target.engine.applyRemote(wires.slice(split));
          await target.engine.endHydration();
          // Echoes still in flight when hydration ends are also suppressed.
          for (const entry of target.applier.applied.slice(split)) {
            expect(
              await target.engine.localChange(
                entry.plain.identity,
                entry.plain.attributes,
                false,
                "explicit",
              ),
            ).toBeNull();
          }

          expect(target.transport.published).toHaveLength(0);
          expect(target.engine.listLiveCookies()).toHaveLength(jarSize);
        },
      ),
      { numRuns: 40 },
    );
  }, 60_000);
});

describe("property 4: identity tuple fidelity", () => {
  it("cookies differing only in host scope, partition key, or source scheme never collide", async () => {
    const spaceId = "space-tuple";
    await fc.assert(
      fc.asyncProperty(
        fc.constantFrom("host-scope", "partition", "scheme"),
        fc.integer({ min: 0, max: IDENTITY_POOL_SIZE - 1 }),
        async (dimension, index) => {
          const clock = new ManualClock();
          const a = await createEngine(spaceId, "dev-a", clock);
          const b = await createEngine(spaceId, "dev-b", clock);
          const base = identityAt(spaceId, index);
          const variant = { ...base };
          if (dimension === "host-scope") {
            variant.hostKey = base.hostKey.startsWith(".")
              ? base.hostKey.slice(1)
              : `.${base.hostKey}`;
          } else if (dimension === "partition") {
            variant.partitionKey =
              base.partitionKey === "" ? "https://partition.example" : "";
          } else {
            variant.sourceScheme =
              base.sourceScheme === "secure" ? "nonsecure" : "secure";
          }

          clock.tick(1);
          const first = must(
            await a.engine.localChange(
              base,
              attrsFor("base"),
              false,
              "explicit",
            ),
          );
          clock.tick(1);
          const second = must(
            await a.engine.localChange(
              variant,
              attrsFor("variant"),
              false,
              "explicit",
            ),
          );

          expect(second.recordId).not.toBe(first.recordId);
          expect(a.engine.listLiveCookies()).toHaveLength(2);

          expect(await b.engine.applyRemote([first, second])).toEqual([
            "applied",
            "applied",
          ]);
          expect(b.engine.listLiveCookies()).toHaveLength(2);
          const values = new Set(
            b.engine.listLiveCookies().map((p) => p.attributes?.value),
          );
          expect(values).toEqual(new Set(["base", "variant"]));
        },
      ),
      { numRuns: 60 },
    );
  }, 60_000);
});

describe("property 5: tombstone GC", () => {
  const RETENTION_MS = 1_000;

  it("never collects young tombstones; pre-delete writes stay blocked while retained", async () => {
    const spaceId = "space-gc";
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 0, max: RETENTION_MS - 2 }),
        async (age) => {
          const clock = new ManualClock();
          const a = await createEngine(spaceId, "dev-a", clock, {
            tombstoneRetentionMs: RETENTION_MS,
          });
          const b = await createEngine(spaceId, "dev-b", clock, {
            tombstoneRetentionMs: RETENTION_MS,
          });
          const identity = makeIdentity(spaceId, "github.com", "sid");

          clock.tick(1);
          const w0 = must(
            await a.engine.localChange(
              identity,
              attrsFor("v0"),
              false,
              "explicit",
            ),
          );
          expect(await b.engine.applyRemote([w0])).toEqual(["applied"]);

          clock.tick(1);
          const tombstone = must(
            await a.engine.localChange(identity, null, true, "explicit"),
          );

          // Concurrent write with pre-delete ancestry and a later HLC.
          clock.tick(1);
          const stale = must(
            await b.engine.localChange(
              identity,
              attrsFor("late"),
              false,
              "explicit",
            ),
          );

          clock.tick(age);
          expect(a.engine.gcTombstones()).toBe(0);
          expect(a.engine.getRecord(tombstone.recordId)).toBeDefined();
          expect(await a.engine.applyRemote([stale])).toEqual([
            "resurrection-blocked",
          ]);
          expect(a.engine.listLiveCookies()).toEqual([]);

          clock.tick(RETENTION_MS + 1);
          expect(a.engine.gcTombstones()).toBe(1);
          expect(a.engine.getRecord(tombstone.recordId)).toBeUndefined();
        },
      ),
      { numRuns: 60 },
    );
  }, 60_000);
});

describe("property 6: offline queue ordering", () => {
  it("offline mutations drain in HLC order and arrive exactly once", async () => {
    const spaceId = "space-queue";
    await fc.assert(
      fc.asyncProperty(
        fc.array(
          fc.record({
            ident: fc.integer({ min: 0, max: IDENTITY_POOL_SIZE - 1 }),
          }),
          {
            minLength: 1,
            maxLength: 10,
          },
        ),
        async (ops) => {
          const clock = new ManualClock();
          const a = await createEngine(spaceId, "dev-a", clock);
          a.engine.setOnline(false);
          for (let i = 0; i < ops.length; i += 1) {
            clock.tick(1);
            must(
              await a.engine.localChange(
                identityAt(spaceId, ops[i]?.ident ?? 0),
                attrsFor(`q${i}`),
                false,
                "explicit",
              ),
            );
          }
          expect(a.transport.published).toHaveLength(0);
          const expectedCount = new Set(ops.map((op) => op.ident)).size;
          expect(a.engine.queueDepth).toBe(expectedCount);

          a.engine.setOnline(true);
          await settle(() => a.transport.published.length === expectedCount);
          expect(a.engine.queueDepth).toBe(0);

          const encoded = a.transport.published.map((r) => encodeHlc(r.hlc));
          expect(encoded).toEqual(
            [...encoded].sort((x, y) => x.localeCompare(y)),
          );
          expect(new Set(encoded).size).toBe(expectedCount);
        },
      ),
      { numRuns: 60 },
    );
  }, 60_000);
});

describe("property 7: unpublished ancestry never reaches the wire", () => {
  /** Offline login followed by `rotations` overwrites; the queue compacts to the newest. */
  async function offlineChain(
    replica: Replica,
    clock: ManualClock,
    identity: ReturnType<typeof identityAt>,
    rotations: number,
  ): Promise<CookieRecordWire> {
    clock.tick(1);
    let newest = must(
      await replica.engine.localChange(identity, attrsFor("login"), false, "explicit"),
    );
    for (let i = 0; i < rotations; i += 1) {
      clock.tick(1);
      newest = must(
        await replica.engine.localChange(identity, attrsFor(`r${i}`), false, "overwrite"),
      );
    }
    expect(replica.engine.queueDepth).toBe(1);
    return newest;
  }

  it("an offline logout → login → n rotations chain converges on a peer holding the logout fence", async () => {
    const spaceId = "space-p7-offline";
    const recordIds = await poolRecordIds(await testSpaceKeys(spaceId), spaceId);
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 1, max: 8 }),
        fc.boolean(),
        async (rotations, chainFirst) => {
          const cluster = await createCluster(spaceId, 2);
          const [a, p] = cluster.replicas;
          if (!a || !p) throw new Error("cluster too small");
          const identity = identityAt(spaceId, 0);

          cluster.clock.tick(1);
          must(await a.engine.localChange(identity, attrsFor("v0"), false, "explicit"));
          await cluster.hub.deliverAll();

          // Offline logout, flushed on its own so the peer holds the fence.
          a.engine.setOnline(false);
          cluster.clock.tick(1);
          const logout = must(await a.engine.localChange(identity, null, true, "explicit"));
          a.engine.setOnline(true);
          await a.engine.flushPending();

          a.engine.setOnline(false);
          const newest = await offlineChain(a, cluster.clock, identity, rotations);
          a.engine.setOnline(true);
          await a.engine.flushPending();
          expect(a.engine.queueDepth).toBe(0);

          const published = must(a.engine.getRecord(newest.recordId)).wire;
          expect(published.hlc).toEqual(newest.hlc);
          expect(published.causalParent).toBe(makeVersionToken(logout.recordId, logout.hlc));

          // Reordered delivery: the chain before the logout, or the hub order.
          if (chainFirst) await p.engine.applyRemote([published]);
          await cluster.hub.deliverAll();

          expect(enginePrint(p.engine, recordIds)).toBe(enginePrint(a.engine, recordIds));
          expect(livePrint(p.engine)).toBe(livePrint(a.engine));
          expect(p.engine.listLiveCookies().map((c) => c.attributes?.value)).toEqual([
            rotations === 0 ? "login" : `r${rotations - 1}`,
          ]);
        },
      ),
      { numRuns: 30 },
    );
  }, 120_000);

  it("also converges through the deferred lane with an interleaved cloud version", async () => {
    const spaceId = "space-p7-deferred";
    const recordIds = await poolRecordIds(await testSpaceKeys(spaceId), spaceId);
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 1, max: 6 }),
        fc.constantFrom("before-chain", "after-chain", "none"),
        fc.boolean(),
        async (rotations, cloudWrite, cloudDeliveredBeforeRelease) => {
          const cluster = await createCluster(
            spaceId,
            2,
            { deferToForeignLease: (denial) => denial.holderKind === "cloud" },
            { enforceLeases: true },
          );
          const [a, p] = cluster.replicas;
          if (!a || !p) throw new Error("cluster too small");
          const c = await addReplica(cluster, spaceId, "cloud-0", { leaseKind: "cloud" });
          const identity = identityAt(spaceId, 0);
          const sameOrigin = identityAt(spaceId, 6); // github.com csrf: same origin id

          cluster.clock.tick(1);
          const v0 = must(await a.engine.localChange(identity, attrsFor("v0"), false, "explicit"));
          await cluster.hub.deliverAll();

          a.engine.setOnline(false);
          cluster.clock.tick(1);
          const logout = must(await a.engine.localChange(identity, null, true, "explicit"));
          a.engine.setOnline(true);
          await a.engine.flushPending();
          await cluster.hub.deliverAll();
          for (const replica of [p, c]) {
            expect(replica.engine.getRecord(logout.recordId)?.cause).toBe("EXPLICIT_DELETE");
          }

          // The cloud run starts and takes the exclusive origin lease.
          const cloud: { wire: CookieRecordWire | null } = { wire: null };
          const cloudWrites = async (): Promise<void> => {
            cluster.clock.tick(1);
            cloud.wire = must(
              await c.engine.localChange(identity, attrsFor("cloud"), false, "explicit"),
            );
          };
          if (cloudWrite === "before-chain") await cloudWrites();
          else {
            cluster.clock.tick(1);
            must(await c.engine.localChange(sameOrigin, attrsFor("csrf"), false, "explicit"));
          }
          expect(cluster.hub.leaseHolder(spaceId, v0.originId)).toEqual({
            holderDeviceId: "cloud-0",
            exclusive: true,
          });

          // A's offline chain bounces off the exclusive lease into the deferred lane.
          a.engine.setOnline(false);
          const newest = await offlineChain(a, cluster.clock, identity, rotations);
          a.engine.setOnline(true);
          await a.engine.flushPending();
          const rejections = await cluster.hub.ackPublishes();
          expect(rejections.map((r) => r.reason)).toEqual(["exclusive_lease"]);
          expect(a.engine.deferredDepth).toBe(1);
          expect(a.engine.queueDepth).toBe(0);

          if (cloudWrite === "after-chain") await cloudWrites();
          if (cloudDeliveredBeforeRelease) await cluster.hub.deliverAll();

          // The run ends: the cloud device releases its leases; the hub
          // broadcasts lease.released and A drains the deferred lane.
          c.engine.setOnline(false);
          await a.engine.retryDeferred();
          expect(await cluster.hub.ackPublishes()).toEqual([]);
          c.engine.setOnline(true);
          await cluster.hub.deliverAll();
          expect(a.engine.deferredDepth).toBe(0);

          const expected =
            cloud.wire !== null && compareHlc(cloud.wire.hlc, newest.hlc) > 0
              ? "cloud"
              : rotations === 0
                ? "login"
                : `r${rotations - 1}`;
          for (const replica of [p, c]) {
            expect(enginePrint(replica.engine, recordIds)).toBe(enginePrint(a.engine, recordIds));
            expect(livePrint(replica.engine)).toBe(livePrint(a.engine));
          }
          const live = must(a.engine.getRecord(newest.recordId));
          expect(live.plain.attributes?.value).toBe(expected);
          // Whatever won, every wire that reached the hub named a published parent.
          if (live.hlc.deviceId === "dev-0") {
            expect(live.wire.causalParent).toBe(makeVersionToken(logout.recordId, logout.hlc));
          }
        },
      ),
      { numRuns: 30 },
    );
  }, 120_000);
});
