const {_electron:electron,expect}=require('@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const out=path.resolve('e2e/exploration/navigation/extra-test-results/round3');
let app,shell,native,base,profile;const results=[];
async function record(name,data){results.push({name,data});console.log(name,JSON.stringify(data).slice(0,1400));await fs.writeFile(path.join(out,'results.json'),JSON.stringify(results,null,2));}
async function snap(){return shell.evaluate(()=>window.pistachio.getSnapshot());}
async function shot(name,page=native){await page.screenshot({path:path.join(out,name+'.png'),timeout:10000});}
async function nav(value){await shell.keyboard.press('Meta+l');await shell.getByTestId('address-input').fill(value);await shell.getByTestId('address-input').press('Enter');await expect(shell.getByTestId('address-input')).toHaveCount(0);await expect.poll(()=>app.windows().some(p=>p.url()===value),{timeout:20000}).toBe(true);native=app.windows().find(p=>p.url()===value);await native.waitForLoadState('domcontentloaded');}
function makePdf(){const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const stream='BT /F1 24 Tf 72 700 Td (Pistachio PDF browsing fixture) Tj ET';objs.push('<< /Length '+Buffer.byteLength(stream)+' >>\nstream\n'+stream+'\nendstream');let pdf='%PDF-1.4\n';const offsets=[0];objs.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return Buffer.from(pdf);}
(async()=>{
 await fs.mkdir(out,{recursive:true});profile=await fs.mkdtemp(path.join(os.tmpdir(),'pistachio-navigation-extra-'));await fs.writeFile(path.join(profile,'qa-upload.txt'),'Harmless upload fixture 2026-09-09');
 const requests=[];const server=http.createServer((req,res)=>{if(req.url==='/document.pdf'){res.writeHead(200,{'Content-Type':'application/pdf'});res.end(makePdf());return;}if(req.url==='/upload'&&req.method==='POST'){let chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>{requests.push({url:req.url,body:Buffer.concat(chunks).toString()});res.writeHead(200,{'Content-Type':'text/plain'});res.end('Upload received');});return;}res.writeHead(200,{'Content-Type':'text/html'});if(req.url==='/popup'){res.end('<title>Popup fixture</title><h1>Popup confirmation</h1><p>This harmless popup returns a message to its opener.</p><button onclick="window.opener.postMessage(\'popup-ok\',location.origin);window.close()">Confirm and close</button>');return;}res.end(`<!doctype html><title>Everyday browsing fixture</title><style>body{font:20px system-ui;margin:40px;line-height:1.6}button{padding:12px;margin:8px}#stage{padding:30px;background:#c6e8cd}#stage:fullscreen{display:grid;place-content:center;font:32px system-ui}input{display:block;margin:20px}</style><h1>Everyday browsing fixture</h1><button id="popup" onclick="window.open('/popup','qa-popup','width=600,height=500')">Open popup</button><p id="popup-result">No popup result</p><label>Attach file<input id="file" type="file" onchange="document.querySelector('#file-result').textContent=this.files[0].name"></label><p id="file-result">No file attached</p><button onclick="const data=new FormData();data.append('file',document.querySelector('#file').files[0]);fetch('/upload',{method:'POST',body:data}).then(r=>r.text()).then(t=>document.querySelector('#upload-result').textContent=t)">Upload attachment</button><p id="upload-result"></p><section id="stage"><h2>Fullscreen content</h2><button onclick="document.querySelector('#stage').requestFullscreen().catch(e=>document.body.dataset.error=e.message)">Enter fullscreen</button></section><p><a href="/document.pdf">Open PDF</a></p><script>window.addEventListener('message',e=>{if(e.origin===location.origin)document.querySelector('#popup-result').textContent=e.data})</script>`);});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
 try{
 app=await electron.launch({cwd:process.cwd(),args:['.'],executablePath:path.resolve('node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),env:{...process.env,PISTACHIO_E2E:'1',PISTACHIO_USER_DATA:profile}});shell=app.windows().find(p=>p.url().endsWith('/index.html'))||await app.waitForEvent('window',{predicate:p=>p.url().endsWith('/index.html')});await nav(base+'/');await record('environment',{base,profile});await shot('01-everyday-fixture');
 // The page's own fullscreen button exercises the actual browser transition.
 await app.evaluate(({webContents},url)=>webContents.getAllWebContents().find(w=>w.getURL()===url).focus(),base+'/');await record('explicit-native-focus-before-click',true);await native.getByRole('button',{name:'Enter fullscreen'}).click();await expect.poll(()=>native.evaluate(()=>document.fullscreenElement?.id),{timeout:15000}).toBe('stage');await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),{timeout:15000}).toBe(true);await record('fullscreen-enter',{element:await native.evaluate(()=>document.fullscreenElement.id),nativeWindow:await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen())});await expect.poll(()=>app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];const b=w.getContentBounds();return w.contentView.children.some(v=>'webContents' in v && v.getVisible() && v.getBounds().x===0 && v.getBounds().width===b.width);}),{timeout:15000}).toBe(true);await shot('06-fullscreen');await record('fullscreen-before-escape',await app.evaluate(({BrowserWindow,webContents})=>({focusedWindow:BrowserWindow.getFocusedWindow()?.id,focusedContents:webContents.getFocusedWebContents()?.getURL()})));await native.keyboard.press('Escape');await expect.poll(()=>native.evaluate(()=>document.fullscreenElement===null),{timeout:15000}).toBe(true).catch(async()=>{await record('fullscreen-escape-failure',{documentStillFullscreen:await native.evaluate(()=>document.fullscreenElement!==null),windowStillFullscreen:await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen())});await shot('06b-escape-failed');await native.evaluate(()=>document.exitFullscreen());await record('fullscreen-recovery','Explicit document.exitFullscreen for test continuation');});await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),{timeout:15000}).toBe(false);await shot('07-fullscreen-exited');await record('fullscreen-final-exit',{recoveredExplicitly:results.some(r=>r.name==='fullscreen-escape-failure')});
 // Open a harmless locally served PDF through the page link.
 await native.getByRole('link',{name:'Open PDF',exact:true}).click();await expect.poll(async()=>{const state=await snap();return state.tabs.find(t=>t.id===state.activeTabId)?.url;},{timeout:20000}).toBe(base+'/document.pdf');await native.waitForLoadState('load');await shot('08-pdf');await record('pdf',{url:native.url(),title:await native.title(),frames:native.frames().map(f=>f.url()),body:await native.locator('body').innerText(),embeds:await native.locator('embed').count()});await shell.getByRole('button',{name:'Back',exact:true}).click();await expect(native).toHaveURL(base+'/');await shot('09-back-from-pdf');await record('pdf-back','passed');
 }catch(e){await record('run-error',String(e.stack));if(native&&!native.isClosed())await shot('99-failure').catch(e=>record('screenshot-error',String(e)));process.exitCode=1;}finally{if(app)await app.close();server.closeAllConnections();server.close();}
})();
