import { _electron as electron, expect } from '@playwright/test';
import { mkdtemp, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createServer } from 'node:http';
const dir=resolve('../../docs/qa/2026-09-09/organization/round2');
await mkdir(dir,{recursive:true});
const server=createServer((req,res)=>{const name=decodeURIComponent(req.url.slice(1))||'Travel planning';res.writeHead(200,{'content-type':'text/html'});res.end(`<html><head><title>${name}</title></head><body style="font:18px system-ui;max-width:720px;margin:60px auto"><h1>${name}</h1><p>Plan a weekend away. Compare destinations, save useful pages, and organize your research.</p><nav><a href="/Museums">Museums</a> · <a href="/Hotels">Hotels</a> · <a href="/Restaurants">Restaurants</a></nav><p><label>Travel notes <textarea placeholder="Write your plans here"></textarea></label></p></body></html>`)});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
const profile=await mkdtemp(join(tmpdir(),'pistachio-organization-qa-'));
await writeFile(join(profile,'settings.json'),JSON.stringify({general:{homeUrl:origin+'/'},layout:{mode:'sidebar',sidebar:'pinned'}}));
let app,shell; const results=[];let seq=0;
async function launch(){app=await electron.launch({args:['.'],cwd:process.cwd(),executablePath:resolve('node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),env:{...process.env,PISTACHIO_E2E:'1',PISTACHIO_USER_DATA:profile}});await expect.poll(()=>app.windows().some(p=>p.url().includes('index.html')&&!p.url().includes('#'))).toBe(true);shell=app.windows().find(p=>p.url().includes('index.html')&&!p.url().includes('#'));await shell.waitForLoadState('domcontentloaded');shell.setDefaultTimeout(5000);await expect(shell.getByTestId('new-tab-button')).toBeVisible();}
const state=()=>shell.evaluate(()=>window.pistachio.getSnapshot());
async function shot(name){
const f=`${String(++seq).padStart(2,'0')}-${name}.png`;
const capture=await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];const frame=await w.capturePage();const size=frame.getSize();const views=await Promise.all(w.contentView.children.filter(c=>'webContents' in c&&'getVisible' in c&&c.getVisible()).map(async c=>{try{return await Promise.race([(async()=>({bounds:c.getBounds(),png:(await c.webContents.capturePage()).toPNG().toString('base64')}))(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('capture timeout')),1500))]);}catch{return null;}}));return{frame:frame.toPNG().toString('base64'),...size,scale:size.width/w.getContentSize()[0],views}});
const data=await shell.evaluate(async c=>{const decode=p=>new Promise((r,j)=>{let im=new Image();im.onload=()=>r(im);im.onerror=j;im.src='data:image/png;base64,'+p});let canvas=document.createElement('canvas');canvas.width=c.width;canvas.height=c.height;let ctx=canvas.getContext('2d');ctx.drawImage(await decode(c.frame),0,0);for(const v of c.views.filter(Boolean))ctx.drawImage(await decode(v.png),Math.round(v.bounds.x*c.scale),Math.round(v.bounds.y*c.scale));return canvas.toDataURL('image/png').split(',')[1]},capture);await writeFile(join(dir,f),Buffer.from(data,'base64'));return f;}
async function step(name,fn){try{const detail=await fn();results.push({name,ok:true,detail,screenshot:await shot(name).catch(e=>'Capture unavailable: '+String(e))});}catch(e){results.push({name,ok:false,error:String(e),screenshot:await shot(name+'-failure').catch(e=>'Capture unavailable: '+String(e)),dom:await shell.locator('body').innerText()});await shell.keyboard.press('Escape').catch(()=>{});}await writeFile(join(dir,'results.json'),JSON.stringify({profile,origin,results},null,2));console.log(JSON.stringify(results.at(-1)));}
async function menu(row,name){await row.click({button:'right'});await shell.getByRole('menuitem',{name,exact:true}).click();}
async function newTab(name){await shell.getByTestId('new-tab-button').click();await shell.getByTestId('address-input').fill(origin+'/'+name);await shell.getByTestId('address-input').press('Enter');await expect.poll(async()=>{const s=await state();return s.tabs.find(t=>t.id===s.activeTabId)?.url}).toBe(origin+'/'+name);}
try{
await launch();
await step('loaded-home',async()=>{const p=app.windows().find(p=>p.url().startsWith(origin));await expect(p.locator('h1')).toBeVisible();return state()});
await step('bookmark-shortcut-ready',async()=>{await shell.getByTestId('sidebar-address').click();await shell.keyboard.press('Escape');await shell.keyboard.press('Meta+Shift+B');await expect(shell.getByTestId('bookmarks-page')).toBeVisible();return {dom:await shell.locator('body').innerText()}});
await step('bookmark-add',async()=>{if(!await shell.getByTestId('bookmarks-page').isVisible()){await shell.getByTestId('sidebar-menu-button').click();await shell.getByTestId('bookmarks-button').click();}await shell.getByTestId('new-bookmark').click();await shell.getByLabel('Address to bookmark').fill(origin+'/Restaurants');await shell.getByTestId('bookmark-add-submit').click();await expect(shell.getByTestId('bookmark-card')).toHaveCount(1);await expect(shell.getByTestId('bookmark-card')).toHaveAttribute('data-status','ready');return {dom:await shell.getByTestId('bookmarks-page').innerText()}});
await step('bookmark-edit',async()=>{await shell.getByTestId('bookmark-card').click();await shell.getByTestId('bookmark-edit').click();await shell.getByTestId('bookmark-editor').getByLabel('Title',{exact:true}).fill('Dinner shortlist');await shell.getByTestId('bookmark-editor').getByLabel('Note',{exact:true}).fill('Outdoor seating');await shell.getByTestId('bookmark-editor-save').click();await expect(shell.getByTestId('bookmark-detail')).toContainText('Dinner shortlist');return {dom:await shell.getByTestId('bookmark-detail').innerText()}});
await step('bookmark-search-note',async()=>{await shell.keyboard.press('Escape');await shell.getByTestId('bookmark-search').fill('outdoor');await expect(shell.getByTestId('bookmark-card')).toHaveCount(1);return {dom:await shell.getByTestId('bookmarks-page').innerText()}});
await step('bookmark-open',async()=>{await shell.getByTestId('bookmark-card').click();await shell.getByTestId('bookmark-open').click();await expect(shell.getByTestId('bookmarks-page')).toBeHidden();return state()});
await step('shortcut-pin-versus-bookmark',async()=>{await shell.getByTestId('sidebar-address').click();await shell.keyboard.press('Escape');await shell.keyboard.press('Meta+D');await expect(shell.getByTestId('pinned-tab')).toHaveCount(1);return {state:await state(),bookmarks:await shell.evaluate(()=>window.pistachio.getBookmarks())}});
await step('close-and-reopen-native',async()=>{await newTab('Museums');const n=(await state()).tabs.length;await menu(shell.getByTestId('human-tab').last(),'Close tab');await app.evaluate(({webContents})=>{const c=webContents.getAllWebContents().find(c=>c.getURL().includes('index.html')&&!c.getURL().includes('#'));c.focus();c.sendInputEvent({type:'keyDown',keyCode:'T',modifiers:['meta','shift']});c.sendInputEvent({type:'keyUp',keyCode:'T',modifiers:['meta','shift']});});await expect.poll(async()=>(await state()).tabs.length,{timeout:2500}).toBe(n);return state()});
await step('settings-layout',async()=>{await shell.getByTestId('sidebar-menu-button').click();await shell.getByTestId('settings-button').click();await shell.getByRole('button',{name:'General',exact:true}).click();return {dom:await shell.getByTestId('settings-page').innerText()}});
await step('top-tabs-layout',async()=>{await shell.getByTestId('layout-mode-top').click();await shell.keyboard.press('Escape');return {state:await state(),dom:await shell.locator('body').innerText()}});
await step('top-new-tab',async()=>{await newTab('Hotels');return state()});
await step('top-tabs-context',async()=>{await shell.getByTestId('human-tab').last().click({button:'right'});return {dom:await shell.getByTestId('context-menu').innerText()}});
await shell.keyboard.press('Escape');
}finally{if(app)await app.close();server.close();}
